# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8312af4e6604b0b40eef391b57b4adb333cba38b10c308f587905cc5116976f522105f983a586e15dfb691b58451ff10432b083e069a39b3b11ebc96d333038e

test:
  secret_key_base: c10f137650c0a58a7a17b094c83d254e3fe3c43595f28b48e0ce62a941ecb9cdaf5b49582f3f90e6673b77ee3e0bc2aee9544a3d224c63910712673f57c17b9e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
